#!/bin/sh
#
# chkconfig: 345 95 05	(1)
# description: DSMWatcher
#
# processname: DSMWatcher
# pidfile: /root/dsmwatcher.pid

prog="DSMWatcher"
RETVAL=0
start () {
	echo -n $"Starting $prog:"
	nohup java8 -Djavax.net.ssl.trustStore=/root/dsm.jks -jar /root/Watcher.jar /root 2>> /dev/null >> /dev/null & echo $! >/root/dsmwatcher.pid
	RETVAL=$?
	echo "Started"
	[ "$RETVAL" = 0 ]  && touch /var/lock/subsys/$prog
	echo
#	echo $PID > /root/dsmwatcher.pid
}

stop () {
	echo -n $"Stopping $prog:"
	kill -9 $(cat /root/dsmwatcher.pid)	
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		echo $"Usage: $0 {start | stop}"
		RETVAL=1
esac
exit $?
